### PR TITLE
refactor(k3s): add sha256sum endpoint for k3s script install

### PR DESCRIPTION
**Pull request by BadgerOps**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [x] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

https://github.com/saltstack-formulas/kubernetes-formula/issues/23
https://github.com/rancher/k3s/issues/2378 

### Describe the changes you're proposing

This change uses the `https://get.k3s.io/sha256` endpoint to validate the hash for the current k3s install script

### Pillar / config required to test the proposed changes

N/A - no pillar changes required, if no `source_hash` set, then it will use the URL

### Debug log showing how the proposed changes work

```
[INFO    ] Running state [/tmp/kubernetes-tmp//k3s-bootstrap.sh] at time 21:56:43.093716
[INFO    ] Executing state file.managed for [/tmp/kubernetes-tmp//k3s-bootstrap.sh]
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'saltmaster', u'tcp://192.168.50.4:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'saltmaster', u'tcp://192.168.50.4:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://192.168.50.4:4506
[DEBUG   ] Trying to connect to: tcp://192.168.50.4:4506
[DEBUG   ] Requesting URL https://get.k3s.io/sha256 using GET method
[DEBUG   ] Using backend: tornado
[DEBUG   ] file.extract_hash: Extracting any supported hash for file matching either of the following: /tmp/kubernetes-tmp//k3s-bootstrap.sh, https://get.k3s.io/vv1.18.10+k3s1/k3s-linux-
[DEBUG   ] file.extract_hash: Line 'd5bdb06c385673e932de17c0cef3c8f5c48bc2143ad06fbaa58ccce4d7766811' contains sha256 hash 'd5bdb06c385673e932de17c0cef3c8f5c48bc2143ad06fbaa58ccce4d7766811', but line did not meet the search criteria
[DEBUG   ] file.extract_hash: Returning the partially identified sha256 hash 'd5bdb06c385673e932de17c0cef3c8f5c48bc2143ad06fbaa58ccce4d7766811'
[DEBUG   ] Requesting URL https://get.k3s.io/vv1.18.10+k3s1/k3s-linux- using GET method
[DEBUG   ] Using backend: tornado
[INFO    ] File changed:
New file
[INFO    ] Completed state [/tmp/kubernetes-tmp//k3s-bootstrap.sh] at time 21:56:43.545494 (duration_in_ms=451.777)
```

Note: All Kitchen tests still pass, as only the binary install is tested. As per this comment: https://github.com/saltstack-formulas/kubernetes-formula/issues/23#issuecomment-732508454 I'm not sure exactly how to split the test for script vs binary, especially since even the test defaults to binary unless `defaults.yaml` is changed to script. If that change was made, we could update the tests to verify the changed paths for script install.

I ran Kitchen tests on all the configured builds, and spot checked 10 or so, all of them had correctly installed k3s, and k3s was running and usable.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### Additional context

Let me know if there is anything else I could/should do in this PR to make it more useful

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
To add CI/CD here is what is needed.   

1. Add following to kitchen.yml
```
  - name: script
    provisioner:
      state_top:
        base:
          '*':
            # kubernetes.clean
            - kubernetes
      pillars:
        top.sls:
          base:
            '*':
              - kubernetes
      pillars_from_files:
        kubernetes.sls: test/salt/pillar/script.sls
    verifier:
      inspec_tests:
        - path: test/integration/script
```
(2) Our `test/salt/pillar/script.sls` file can be copy of `test/salt/pillar/default.sls` and value changed to `"script"`.
(3) Our `test/integration/script` directory can be copy of `test/integration/default` with some checks for script.  You could run k3s installer script manually and learn what environment variables it supports and what tests are needed by manual checks (what does script do).  Because upstream were lacking RedHat CI/CD for script on CentOS, I did start adding CI/CD tests for script to `redhat`  so that file has clues regarding what unit tests are needed: https://github.com/saltstack-formulas/kubernetes-formula/blob/master/test/integration/redhat/controls/default_spec.rb

(4) Finally you update `.travis.yml` and add new line to test script and redhat.

**Comment by BadgerOps** [comment]
Ok @noelmcloughlin I've got all that working, here's some of the output from the kitchen tests. 
```
     ✔  File /etc/systemd/system/k3s.service is expected to exist
     ✔  File /etc/systemd/system/k3s.service is expected not to be directory
     ✔  File /etc/systemd/system/k3s.service type is expected to eq :file
     ✔  File /usr/local/bin/k3s-killall.sh is expected to exist
     ✔  File /usr/local/bin/k3s-killall.sh is expected not to be directory
     ✔  File /usr/local/bin/k3s-killall.sh type is expected to eq :file
     ✔  File /etc/rancher/k3s/k3s.yaml is expected to exist
     ✔  File /etc/rancher/k3s/k3s.yaml is expected not to be directory
     ✔  File /etc/rancher/k3s/k3s.yaml type is expected to eq :file
     ✔  File /usr/local/bin/k3s is expected to be file
     ✔  File /usr/local/bin/k3s is expected not to be directory
     ✔  File /etc/rancher/k3s is expected to be directory
     ✔  File /etc/rancher/k3s is expected not to be file
     ✔  File /var/lib/rancher/k3s/server/cred/admin.kubeconfig is expected to exist
     ✔  File /var/lib/rancher/k3s/server/cred/admin.kubeconfig is expected not to be directory
     ✔  File /var/lib/rancher/k3s/server/cred/admin.kubeconfig type is expected to eq :file
     ✔  File /var/lib/rancher/k3s/agent/k3scontroller.kubeconfig is expected to exist
     ✔  File /var/lib/rancher/k3s/agent/k3scontroller.kubeconfig is expected not to be directory
     ✔  File /var/lib/rancher/k3s/agent/k3scontroller.kubeconfig type is expected to eq :file
     ✔  File /var/lib/rancher/k3s/server/node-token is expected to be symlink
     ✔  File /var/lib/rancher/k3s/server/node-token is expected to be file
     ✔  File /var/lib/rancher/k3s/server/node-token is expected not to be directory
```
I've got one follow on question - should we only test the k3s changes in the script folder? I feel like it doesn't really make sense to duplicate all the other (default) tests in the script test folder, just apply & test the k3s state. What do you think? 

What I'm considering adding to travis.yaml:
```
    # k3s script install tests
    - env: INSTANCE=script-debian-10-master-py3
    - env: INSTANCE=script-ubuntu-1804-master-py3
    - env: INSTANCE=script-centos-8-master-py3
    - env: INSTANCE=script-fedora-31-master-py3
    - env: INSTANCE=script-opensuse-leap-151-master-py3
    - env: INSTANCE=script-amazonlinux-2-master-py3
```

Edit: for example, running just the k3s state takes only ~25s to build/test on the debian 10 image:
```
# time bundle exec kitchen verify script-debian-10-master-py3

<snip salt logs>

       Succeeded: 9 (changed=3)
       Failed:    0
       ------------
       Total states run:     9
       Total run time:  12.884 s
       Downloading files from <script-debian-10-master-py3>
       Finished converging <script-debian-10-master-py3> (0m19.62s).
-----> Setting up <script-debian-10-master-py3>...
       Finished setting up <script-debian-10-master-py3> (0m0.00s).
-----> Verifying <script-debian-10-master-py3>...
       Loaded script 

Profile: kubernetes formula (script)
Version: (not specified)
Target:  ssh://kitchen@localhost:32772

  ✔  kubernetes archive: should be installed
     ✔  File /etc/systemd/system/k3s.service is expected to exist
     ✔  File /etc/systemd/system/k3s.service is expected not to be directory
     ✔  File /etc/systemd/system/k3s.service type is expected to eq :file
     ✔  File /usr/local/bin/k3s-killall.sh is expected to exist
     ✔  File /usr/local/bin/k3s-killall.sh is expected not to be directory
     ✔  File /usr/local/bin/k3s-killall.sh type is expected to eq :file
     ✔  File /etc/rancher/k3s/k3s.yaml is expected to exist
     ✔  File /etc/rancher/k3s/k3s.yaml is expected not to be directory
     ✔  File /etc/rancher/k3s/k3s.yaml type is expected to eq :file
     ✔  File /usr/local/bin/k3s is expected to be file
     ✔  File /usr/local/bin/k3s is expected not to be directory
     ✔  File /etc/rancher/k3s is expected to be directory
     ✔  File /etc/rancher/k3s is expected not to be file
     ✔  File /var/lib/rancher/k3s/server/cred/admin.kubeconfig is expected to exist
     ✔  File /var/lib/rancher/k3s/server/cred/admin.kubeconfig is expected not to be directory
     ✔  File /var/lib/rancher/k3s/server/cred/admin.kubeconfig type is expected to eq :file
     ✔  File /var/lib/rancher/k3s/agent/k3scontroller.kubeconfig is expected to exist
     ✔  File /var/lib/rancher/k3s/agent/k3scontroller.kubeconfig is expected not to be directory
     ✔  File /var/lib/rancher/k3s/agent/k3scontroller.kubeconfig type is expected to eq :file
     ✔  File /var/lib/rancher/k3s/server/node-token is expected to be symlink
     ✔  File /var/lib/rancher/k3s/server/node-token is expected to be file
     ✔  File /var/lib/rancher/k3s/server/node-token is expected not to be directory


Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 22 successful, 0 failures, 0 skipped
       Finished verifying <script-debian-10-master-py3> (0m0.50s).
-----> Test Kitchen is finished. (0m25.27s)
bundle exec kitchen verify script-debian-10-master-py3  1.25s user 0.26s system 5% cpu 25.717 total
```

**Comment by noelmcloughlin** [comment]
Looks good, Great work.  Have good look at `.travis.yml` and see what is best - if we run too many jobs it uses credit on Travis (I have exhausted my free credit this month).    Personally, I think running scripts lack transparency so I prefer to promote tarball/package/container over scripts.  For Travis maybe script on Ubuntu and RedHat is enough IMHO.  Upstream K3s is missing CI/CD for script on CentOS btw so it is interesting if its working here first ;-)

**Comment by BadgerOps** [comment]
Ok, thanks for that clarification. I realize I probably shouldn't have amended & force pushed that, another commit with `tests(k3s)` would have been better right? I was intending on pushing a commit as an example to show, didn't think through it going into the existing PR, so apologies for that. 

I'll fix the kitchen.yaml newline issue + update .travis.yml

**Comment by noelmcloughlin** [comment]
I force push to PR's all the time. No worries.

**Comment by BadgerOps** [comment]
>  Upstream K3s is missing CI/CD for script on CentOS btw so it is interesting if its working here first ;-)


:facepalm: so on that... Initially I'd been testing on a CentOS vagrant box that I've used for other testing (bad badger, not starting from clean), as I didn't have kitchen set up to work locally. Re-testing with the 'correct' method definitely exposes this problem. So: k3s tests against Ubuntu / Debian then? :joy: I can definitely confirm those two are working correctly, haha. This has been a good learning experience, thank you for the feedback.

**Comment by BadgerOps** [comment]
Oh hey, Amazon Linux _does_ work though:
```
       ------------
       Succeeded: 8 (changed=4)
       Failed:    0
       ------------
       Total states run:     8
       Total run time:  21.490 s
       Downloading files from <script-amazonlinux-2-master-py3>
       Finished converging <script-amazonlinux-2-master-py3> (0m28.81s).
-----> Setting up <script-amazonlinux-2-master-py3>...
       Finished setting up <script-amazonlinux-2-master-py3> (0m0.00s).
-----> Verifying <script-amazonlinux-2-master-py3>...
       Loaded script 

Profile: kubernetes formula (script)
Version: (not specified)
Target:  ssh://kitchen@localhost:32779

  ✔  kubernetes archive: should be installed
     ✔  File /etc/systemd/system/k3s.service is expected to exist
     ✔  File /etc/systemd/system/k3s.service is expected not to be directory
     ✔  File /etc/systemd/system/k3s.service type is expected to eq :file
     ✔  File /usr/local/bin/k3s-killall.sh is expected to exist
     ✔  File /usr/local/bin/k3s-killall.sh is expected not to be directory
     ✔  File /usr/local/bin/k3s-killall.sh type is expected to eq :file
     ✔  File /etc/rancher/k3s/k3s.yaml is expected to exist
     ✔  File /etc/rancher/k3s/k3s.yaml is expected not to be directory
     ✔  File /etc/rancher/k3s/k3s.yaml type is expected to eq :file
     ✔  File /usr/local/bin/k3s is expected to be file
     ✔  File /usr/local/bin/k3s is expected not to be directory
     ✔  File /etc/rancher/k3s is expected to be directory
     ✔  File /etc/rancher/k3s is expected not to be file
     ✔  File /var/lib/rancher/k3s/server/cred/admin.kubeconfig is expected to exist
     ✔  File /var/lib/rancher/k3s/server/cred/admin.kubeconfig is expected not to be directory
     ✔  File /var/lib/rancher/k3s/server/cred/admin.kubeconfig type is expected to eq :file
     ✔  File /var/lib/rancher/k3s/agent/k3scontroller.kubeconfig is expected to exist
     ✔  File /var/lib/rancher/k3s/agent/k3scontroller.kubeconfig is expected not to be directory
     ✔  File /var/lib/rancher/k3s/agent/k3scontroller.kubeconfig type is expected to eq :file
     ✔  File /var/lib/rancher/k3s/server/node-token is expected to be symlink
     ✔  File /var/lib/rancher/k3s/server/node-token is expected to be file
     ✔  File /var/lib/rancher/k3s/server/node-token is expected not to be directory


Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 22 successful, 0 failures, 0 skipped
       Finished verifying <script-amazonlinux-2-master-py3> (0m0.94s).
-----> Test Kitchen is finished. (0m35.07s)
bundle exec kitchen verify script-amazonlinux-2-master-py3  1.16s user 0.23s system 3% cpu 35.564 total

```

**Comment by noelmcloughlin** [comment]
Travis needs fixing.  I am pretty sure I tested the script successfully on CentOS7 but if travis keeps failing you could comment out the failing "redhat" jobs in `.travis.yml` and try to fix in a different PR.

**Comment by noelmcloughlin** [comment]
Saltstack Travis CI has run out of free credits. So Travis has stopped running against PRs.

> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

**Comment by BadgerOps** [comment]
Ok, just brought it back to only run tests against the ubuntu1804 container for now. Bummer that we're out of credits!

**Review by noelmcloughlin — APPROVED** [review]
LGTM.  Maybe on 1st December, you could check Travis CI is working. Bad timing. Thanks buddy @BadgerOps

**Pull request merged**
